(ios_config_segment) @indent
(ping_output) @indent
(traceroute_output) @indent
(ip_int_brief_output) @indent
(version_output) @indent
(inventory_output) @indent
(interface_status_output) @indent
(dir_output) @indent
(diagnostic_output) @indent
(output_content) @indent
